version: "3.8"

services:
  atlas-dashboard-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    environment:
      PORT: 3001
      NODE_ENV: production
    command: node .next/standalone/server.js
